#!/usr/bin/env python3
"""gen_subjects.py -- the syntax census's short subjects: `subjects/`
(gitignored) + `manifest.tsv` (committed).

ONE SUBJECT FAMILY FOR EVERY PATTERN. Every pattern here exercises one
construct in a plain body drawn from one small vocabulary (censustext.py),
so a subject typed as construct X's whole-string HIT is, for the other
eighty-nine patterns, a realistic miss or near-miss -- which is what keeps
the cell inside one night: the harness runs every pattern over every
subject in both short regimes, and the cell is linear in patterns x
subjects (NOTES.md, "Cell-time estimate").

TWO FAMILIES:

  FIELDS  2-14 B whole-string candidates for the `match` regime, each the
          designed hit of at least one pattern and, where a construct has a
          semantic edge, the designed near-miss of another: `item done` /
          `item done\\n` / `item\\ndone` / `item\\r\\ndone` separate `$`,
          `\\Z`, `\\z`, `(?s)`, `\\R` and `\\v`; `the the` is the
          backreference hit; `<b>bold</b>` the named-backreference hit;
          `(a(b)c)` the recursion hit; `aaab` the possessive / atomic edge
          (`a+ab` matches it, `a++ab` cannot); `abc` the atomic-alternation
          edge (`(?>a|ab)c` fails where `(?:a|ab)c` would not); `Cat` / `CAT`
          the option-reset edge (`(?i)c(?^)at` takes the first and not the
          second); `caf\\xe9` the Latin-1 letter `\\p{L}` sees and `\\w`
          does not; `bell\\x07end` the control-byte escapes' hit.

  LINES   <= 256 B of the same vocabulary for the `search_short` regime:
          prose with a doubled word, an order line with a date, a time, an
          address, a price and a hex literal, a tag line with one mismatched
          close, a paren line with one unbalanced open, a key=value line in
          four spellings, a multi-line block with `\\n` and one with
          `\\r\\n`, a mixed-case line, a quoted-string line with one
          unterminated quote, a Latin-1 line, and a 40-byte `a` run followed
          by the possessive shapes.

Every subject is committed as a MANIFEST ROW (id, len, sha256, description,
periodic) and regenerated byte for byte; the `description` column names the
family and the ARM in a fixed spelling -- `field/hit`, `field/edge`,
`line/prose`, `line/structured` -- so a reader of a record can group by what
a subject was built to do without a sixth manifest column.

Deterministic by construction: nothing here is drawn from a generator, the
bytes are typed.
"""
import hashlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import censustext as ct  # noqa: E402

OUT = os.path.join(HERE, "subjects")
MANIFEST = os.path.join(HERE, "manifest.tsv")

# The band, and the sidecar's `short_search_max_bytes`: every line is held
# under it, so both short regimes see the same subjects.
MAX_LINE = 256

# (id, description, bytes)
FIELDS = (
    ("f-cat", "field/hit `cat`: the plain word every class, group, "
     "alternation and modifier body is built on", b"cat"),
    ("f-CAT", "field/edge `CAT`: `(?i)cat`'s hit; `(?i)c(?^)at`'s and "
     "`(?i)c(?-i)at`'s designed MISS (the reset re-cases `at`)", b"CAT"),
    ("f-Cat", "field/edge `Cat`: the option-reset shapes' hit -- caseless "
     "`c`, exact `at`", b"Cat"),
    ("f-concat", "field/edge `concatenate`: `\\Bcat\\B`'s hit and "
     "`\\bcat\\b`'s designed miss (the word is inside a longer one)",
     b"concatenate"),
    ("f-abc", "field/edge `abc`: `(?>a|ab)c` FAILS on it (the atomic "
     "group commits to `a`), `(?:ab)+` takes its first two bytes",
     b"abc"),
    ("f-ac", "field/hit `ac`: `(?>a|ab)c`'s whole-string hit -- the "
     "atomic alternation's first branch, then `c`", b"ac"),
    ("f-abba", "field/hit `abba`: `(\\w)(\\w)\\2\\1`'s whole-string hit",
     b"abba"),
    ("f-aaab", "field/edge `aaab`: `a+b`, `a+ab`, `(?>a+)b`, `a*+b`, "
     "`a{1,2}+b`, `a+(*SKIP)b` hit it; `a++ab` cannot (the possessive "
     "plus keeps the last `a`)", b"aaab"),
    ("f-item", "field/hit `item`: `item(?! done)`'s and "
     "`item(*ACCEPT)done`'s whole-string hit", b"item"),
    ("f-done", "field/hit `done`: `done$`, `done\\Z`, `done\\z` and "
     "`(?m)done$` whole-string hit (the lookbehind shapes cannot hit whole: "
     "nothing precedes offset 0)", b"done"),
    ("f-item-done", "field/hit `item done`: the lookaround, `(?s)`, `\\040` "
     "and `$`/`\\Z`/`\\z` bodies' hit with NO trailing newline",
     b"item done"),
    ("f-item-done-nl", "field/edge `item done\\n`: `done$` and `done\\Z` "
     "match before the final newline, `done\\z` does not", b"item done\n"),
    ("f-item-nl-done", "field/edge `item\\ndone`: `item\\ndone`, `\\R`, "
     "`\\v+`, `(?s)item.done` hit; `(?m)^` and `(?m)$` fire at the "
     "internal newline; `it\\Nm`'s companion", b"item\ndone"),
    ("f-item-crlf-done", "field/edge `item\\r\\ndone`: `\\R` matches the "
     "pair as one newline, `\\v+` as two bytes, `item\\ndone` not at all",
     b"item\r\ndone"),
    ("f-num", "field/hit `42`: `\\d+`'s whole-string hit", b"42"),
    ("f-date", "field/hit `2026-09-05`: the subroutine-call shapes "
     "(`(\\d{2})\\g<1>`, `(?+1)(\\d{2})`, `(\\d{2})(?-1)`, `(?P>d)`) hit "
     "its first four digits under search and none of it whole",
     b"2026-09-05"),
    ("f-time", "field/hit `12:34`: the `(?(DEFINE)...)` shape's "
     "whole-string hit", b"12:34"),
    ("f-year", "field/hit `2026`: the four subroutine-call spellings' "
     "whole-string hit (two digits, then the group called again)", b"2026"),
    ("f-ident", "field/hit `foo_bar9`: `\\w+` whole, `[[:alpha:]]+` and "
     "`\\p{L}+` only a prefix", b"foo_bar9"),
    ("f-kv", "field/hit `key=value`: `key\\h*=\\h*value` and `key=\\K\\w+` "
     "(reported span 4-9)", b"key=value"),
    ("f-kv-tab", "field/hit `key\\tvalue`: the `\\t` escape's whole-string "
     "hit", b"key\tvalue"),
    ("f-dup", "field/hit `the the`: the numbered, relative, python-style "
     "and `(?J)` backreference shapes' whole-string hit", b"the the"),
    ("f-tag", "field/hit `<b>bold</b>`: the named backreference's "
     "whole-string hit", b"<b>bold</b>"),
    ("f-parens", "field/hit `(a(b)c)`: the four recursion shapes' "
     "whole-string hit at nesting depth 2", b"(a(b)c)"),
    ("f-parens-open", "field/edge `(a(bc)`: unbalanced -- the recursion "
     "shapes take `(bc)` under search and nothing whole", b"(a(bc)"),
    ("f-quoted", "field/hit `\"hello\"`: `\".*?\"` and `(?U)\".+\"` "
     "whole-string hit", b"\"hello\""),
    ("f-fx", "field/hit `f(x)`: `\\Qf(x)\\E`'s whole-string hit", b"f(x)"),
    ("f-hash", "field/hit `#42`: the floor's ONLY hit among the fields",
     b"#42"),
    ("f-cafe", "field/edge `caf\\xe9`: `\\p{L}+` and `caf\\x{e9}` take it "
     "whole; `\\w+` and `[[:alpha:]]+` stop at the Latin-1 byte",
     b"caf\xe9"),
    ("f-bell", "field/hit `bell\\x07end`: `bell\\cGend`'s whole-string hit",
     b"bell\x07end"),
)

LINES = (
    ("l-prose", "line/prose plain words with `cat`, `dog`, `item done`, no "
     "doubled word",
     b"the cat sat on the mat and the dog did not care that the item "
     b"was done at all"),
    ("l-dup", "line/prose two doubled words (`the the`, `was was`) and "
     "`abba`", b"we saw the the cat and it was was fine and abba sang"),
    ("l-order", "line/structured an order line: integer, date, time, "
     "address, price, hex literal, `#42` (the floor's only line hit)",
     b"order 42 shipped 2026-09-05 at 12:34 to bob@example.com for "
     b"$12.50 hex 0x1F ticket #42"),
    ("l-tags", "line/structured four tag pairs, one closed by the WRONG "
     "tag, then a bare `<item>` (the conditional's yes-branch)", b"<b>bold</b> and <i>italic</i> and <b>broken</i> and "
     b"<u>under</u> and <item>"),
    ("l-parens", "line/structured balanced expressions to depth 3 and one "
     "unbalanced open", b"f(x) = g(h(x), (y)) + (z(w(v))) - (broken"),
    ("l-kv", "line/structured key=value in four spellings (`=`, ` = `, "
     "`\\t=\\t`, `= `) and `colour=red`",
     b"key=value key = other key\t=\ttab mode= off colour=red"),
    ("l-multi", "line/structured three LF lines, the last `done`, with a "
     "final newline", b"item one\nitem two\ndone\n"),
    ("l-crlf", "line/structured the same block with CRLF line ends",
     b"item one\r\nitem two\r\ndone\r\n"),
    ("l-case", "line/prose the word `cat` in five casings, then "
     "`concatenate` and `cats`", b"Cat CAT cat cAt CaT concatenate cats"),
    ("l-quoted", "line/structured two quoted strings, a single-quoted one, "
     "one unterminated", b"say \"hello\" and \"hi there\" and 'bye' and "
     b"\"unterminated"),
    ("l-latin1", "line/prose four Latin-1 words", b"caf\xe9 na\xefve "
     b"r\xe9sum\xe9 \xe0 la carte"),
    ("l-run", "line/structured a 40-byte `a` run then `b`, then the "
     "possessive and atomic edge shapes", b"xx" + b"a" * 40 + b"b aaab aab ab ac"),
)


def build():
    out = []
    seen = set()
    for sid, desc, body in FIELDS + LINES:
        assert sid not in seen, sid
        seen.add(sid)
        assert "\t" not in desc, sid
        assert len(body) <= MAX_LINE, (sid, len(body))
        out.append((sid, desc, body))
    return out


def main():
    subjects = build()
    os.makedirs(OUT, exist_ok=True)
    rows = ["id\tlen\tsha256\tdescription\tperiodic"]
    for sid, desc, body in subjects:
        with open(os.path.join(OUT, sid + ".bin"), "wb") as f:
            f.write(body)
        rows.append("%s\t%d\t%s\t%s\t%s" % (
            sid, len(body), hashlib.sha256(body).hexdigest(), desc,
            ct.periodic_field(body)))
    with open(MANIFEST, "w", encoding="utf-8", newline="\n") as mf:
        mf.write("\n".join(rows) + "\n")
    sizes = [len(b) for _s, _d, b in subjects]
    print("gen_subjects: %d subjects (%d fields + %d lines, %d B, %d..%d) "
          "-> %s, manifest -> %s"
          % (len(subjects), len(FIELDS), len(LINES), sum(sizes), min(sizes),
             max(sizes), OUT, MANIFEST))
    return 0


if __name__ == "__main__":
    sys.exit(main())
