#!/usr/bin/env python3
"""tools/program_identity.py -- [B79] THE PROGRAM-IDENTITY CENSUS for a
cross-pin pair: which pcrec artifacts did NOT change between two pins?

A cross-pin report's NULL-CONTROL BAND (inbox I-93 block B, I-104;
`docs/design/null_band_v1.md`) is computed from the cells whose artifact is
PROGRAM-IDENTICAL on both sides of the pin boundary -- a Δ on such a cell
measures the between-window component the within-window IQR cannot see.
This tool decides "program-identical" from OUR OWN build step, never from
pcrec's `nullctl.json` (I-104: "we would rather you computed it than
trusted ours"; theirs is accepted only as `--cross-check`).

WHY A TOOL AND NOT A RECORD FIELD (a finding, [B79]): the records carry
NO hash of the emitted program. A compile row's `engine_metadata` has
`emit_bytes`/`emit_code_bytes`/`artifact_bytes` and the mechanism stamps,
and none of them is an identity: every re-pin adds stamp lines that move
the sizes of EVERY artifact by a pin-specific constant (B84_STAMP_LINE_*),
and two different programs can share a size. So the census RE-EMITS each
pattern at both pins with the binaries this project's own `pin.sh` built
(`build/pcrec-<pin>/build/pcrec` -- the SAME binaries the records' own
`emit-c` phase ran, `testee.binary.sha256` is checked against them) under
each config's OWN pcrec flags (read from the RECORD's `testee.build_flags`,
never retyped), and compares the normalized `.c` + `.h`. Carrying a
normalized program hash in the compile row itself would make this tool a
cross-check rather than the source -- OWED as a schema/adapter ruling
(docs/dev/lanes/b79nullband_report.md).

NORMALIZATION (the ONLY lines ignored -- pcrec's own nullctl.py rule,
generalised from its one named stamp to any ONE-SIDED stamp):
  1. the `/* Generated by pcrec ... */` provenance line (it names the abi
     and the version string, which move at every pin by construction);
  2. the `.abi = N,` initializer (the abi integer, likewise);
  3. every `#define NAME ...` line whose NAME is `#define`d on ONE side
     only -- a stamp the other pin does not emit at all (RX_REQ_RUN at
     b1885a83, RX_REQ_WHY at 6ef76820, ...). A macro present on BOTH
     sides is compared VERBATIM, so a stamp whose VALUE moved (RX_REQ_BYTE
     114 -> 98) is a changed program, and it always is: the stamp names
     the emitted code's own constant.
Everything else -- every statement, every table, every other `#define` --
is compared byte for byte. Comments are not an issue: the census emits
WITHOUT `-fcomments` (comments are OFF by default at every pin since
25b1984f, D112), which the `.so` is proven independent of
(testees/pcrec/CLAUDE.md, [B58]).

COVARIATE NOT IN THE IDENTITY (stated, not hidden): OUR shim
(`testees/pcrec/shim.c`) is compiled into every artifact's `.so` beside
the emitted program and changes at most re-pins (a new stamp read). It
moves identically for the identical AND the changed population of a pair,
so its effect (e.g. a layout shift -- [B22]'s `year4` ELF-page finding)
lands INSIDE the null band, where it belongs: the band is the noise
floor of "the pin moved, this program did not".

OUTPUT: `reports/identity/<subbench>@<version>/<engine>_<old>__<new>.tsv`
-- deterministic (no timestamp), re-derivable (`--check` diffs), committed
beside the reports that read it. `pcrecbench report` finds it by that path
for every cross-pin pair it renders and prints its sha256 in the report's
null-band section.

Usage:
    python3 tools/program_identity.py --subbench capability --version 0.1 \\
        --old 8d716693 --new b1885a83 [--cross-check nullctl.json] [--check]

Compile-only (no gcc, no timing): light, but it runs ~1,500 pcrec emits --
announce it on a shared box (BD3).
"""

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(HERE)
sys.path.insert(0, REPO_ROOT)

from pcrecbench import subbench as _sb  # noqa: E402
from pcrecbench import record as _rec  # noqa: E402

PIN_SH = os.path.join(REPO_ROOT, "testees", "pcrec", "pin.sh")
CENSUS_VERSION = "program_identity v1"
C_ENV = dict(os.environ, LC_ALL="C", LANG="C")

FORMS = ("plain", "whole-subject")
COLUMNS = ["config", "pattern_id", "form", "verdict", "old_sha256",
           "new_sha256", "ignored_one_sided_macros"]

_GEN_LINE = re.compile(r"^/\* Generated by pcrec\b")
_ABI_LINE = re.compile(r"^\s*\.abi\s*=\s*\d+\s*,?\s*$")
_DEFINE = re.compile(r"^\s*#\s*define\s+([A-Za-z_][A-Za-z0-9_]*)")


def census_path(subbench, version, engine, old, new, root=REPO_ROOT):
    return os.path.join(root, "reports", "identity", f"{subbench}@{version}",
                        f"{engine}_{old}__{new}.tsv")


def _defined_names(text):
    return {m.group(1) for ln in text.splitlines()
            for m in (_DEFINE.match(ln),) if m}


def normalize_pair(old_text, new_text):
    """-> (old_norm, new_norm, ignored) -- the three-rule normalization in
    the module docstring, applied to BOTH sides against each other."""
    old_names, new_names = _defined_names(old_text), _defined_names(new_text)
    one_sided = old_names ^ new_names

    def norm(text):
        out = []
        for ln in text.splitlines():
            if _GEN_LINE.match(ln) or _ABI_LINE.match(ln):
                continue
            m = _DEFINE.match(ln)
            if m and m.group(1) in one_sided:
                continue
            out.append(ln)
        return "\n".join(out) + "\n"

    return norm(old_text), norm(new_text), sorted(one_sided)


def sha(text):
    return hashlib.sha256(text.encode("utf-8", "surrogateescape")).hexdigest()


def pin_binary(pin):
    proc = subprocess.run([PIN_SH, "--path", pin], capture_output=True,
                          text=True, env=C_ENV, timeout=120)
    if proc.returncode != 0:
        raise SystemExit(f"pin.sh --path {pin} failed: {proc.stderr}")
    path = proc.stdout.strip()
    if not os.path.isfile(path):
        raise SystemExit(f"{pin}: no built binary at {path} (run pin.sh {pin})")
    return path


def file_sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _cli_shape(binary, workdir):
    """`--pattern` (pcrec D118, 8d716693+) or `--` (before it) -- probed on
    a trivial pattern, never guessed from the pin name."""
    out = os.path.join(workdir, "probe.c")
    r = subprocess.run([binary, "-p", "rx", "-o", out, "--pattern", "a"],
                       capture_output=True, env=C_ENV, timeout=60)
    if r.returncode == 0:
        return "--pattern"
    r = subprocess.run([binary, "-p", "rx", "-o", out, "--", "a"],
                       capture_output=True, env=C_ENV, timeout=60)
    if r.returncode == 0:
        return "--"
    raise SystemExit(f"{binary}: neither CLI shape emits a trivial pattern")


def emit(binary, shape, flags, pattern, workdir):
    """-> the emitted .c + .h text, or None on a refusal. Same argv shape
    as testees/pcrec/adapter.py `_compile_one`'s phase 1, minus
    `-fcomments` (see the module docstring)."""
    os.makedirs(workdir, exist_ok=True)
    out = os.path.join(workdir, "a.c")
    for p in (out, out[:-2] + ".h"):
        if os.path.exists(p):
            os.unlink(p)
    argv = ([binary, "-p", "rx"] + list(flags) + ["-o", out, shape]
            + [bytes(pattern)])
    r = subprocess.run(argv, capture_output=True, env=C_ENV, timeout=600)
    if r.returncode != 0:
        return None
    parts = []
    for p in (out, out[:-2] + ".h"):
        if os.path.exists(p):
            with open(p, "rb") as fh:
                parts.append(fh.read().decode("utf-8", "surrogateescape"))
    return "\n/* ---- header ---- */\n".join(parts)


def newest_records(store_dir, subbench, version, engine, pin):
    """{config_slug: record path} -- the newest `measured` record per
    testee_id of this engine at this pin (the reporter's own OD-B15 rule,
    answered from the index alone)."""
    idx = os.path.join(store_dir, "index.tsv")
    best = {}
    with open(idx, encoding="utf-8") as fh:
        cols = fh.readline().rstrip("\n").split("\t")
        for ln in fh:
            row = dict(zip(cols, ln.rstrip("\n").split("\t")))
            if row["subbench"] != subbench or row["version"] != version:
                continue
            if row["status"] != "measured":
                continue
            tid = row["testee_id"]
            parts = tid.split("_", 2)
            if len(parts) != 3 or parts[0] != engine or parts[1] != pin:
                continue
            slug = parts[2]
            if slug not in best or row["timestamp"] > best[slug][0]:
                best[slug] = (row["timestamp"], row["path"])
    out = {}
    for slug, (_ts, path) in best.items():
        if not os.path.isabs(path):
            cand = os.path.join(store_dir, path)
            path = cand if os.path.exists(cand) else \
                os.path.join(os.path.dirname(store_dir), path)
        out[slug] = path
    return out


def record_setup(path):
    with open(path, encoding="utf-8") as fh:
        return json.loads(fh.readline())


_FLAGS_RE = re.compile(r"pcrec flags ([^;]*);")


def flags_of(setup):
    m = _FLAGS_RE.search(setup["testee"].get("build_flags", ""))
    if not m:
        raise SystemExit(f"{setup['testee']['testee_id']}: build_flags carries "
                         f"no `pcrec flags ...;` clause")
    return m.group(1).split()


def build_census(subbench, version, old, new, store_dir, engine="pcrec",
                 log=sys.stderr):
    sb = _sb.find(subbench)
    if sb.version != version:
        raise SystemExit(f"bench/{subbench} is at {sb.version}, not {version}")
    old_recs = newest_records(store_dir, subbench, version, engine, old)
    new_recs = newest_records(store_dir, subbench, version, engine, new)
    slugs = sorted(set(old_recs) & set(new_recs))
    if not slugs:
        raise SystemExit(f"no config measured at both {old} and {new}")
    bins = {old: pin_binary(old), new: pin_binary(new)}
    meta = [f"# {CENSUS_VERSION}; subbench={subbench}@{version}; "
            f"engine={engine}; old={old}; new={new}",
            f"# binaries: {old}={file_sha256(bins[old])}; "
            f"{new}={file_sha256(bins[new])}",
            "# normalization: dropped = the `/* Generated by pcrec` line, the "
            "`.abi = N,` initializer, and every `#define` whose name is "
            "defined on ONE side only; everything else compared verbatim "
            "(.c + .h, emitted WITHOUT -fcomments)",
            "# generated by: tools/program_identity.py (docs/design/null_band_v1.md)"]
    rows = []
    cache = {}
    with tempfile.TemporaryDirectory(dir=os.environ.get("TMPDIR")) as tmp:
        shapes = {p: _cli_shape(b, tmp) for p, b in bins.items()}
        for slug in slugs:
            so, sn = record_setup(old_recs[slug]), record_setup(new_recs[slug])
            for side, s in ((old, so), (new, sn)):
                want = s["testee"].get("binary", {}).get("sha256")
                if want and want != file_sha256(bins[side]):
                    raise SystemExit(f"{s['testee']['testee_id']}: the record's "
                                     f"binary sha256 is not build/pcrec-{side}'s")
            fo, fn = flags_of(so), flags_of(sn)
            if fo != fn:
                raise SystemExit(f"{slug}: flags differ across the pin "
                                 f"({fo} vs {fn}) -- not one config twice")
            canon = {p["pattern_id"]: p["canonical_sha256"] for p in sn["patterns"]}
            meta.append(f"# config {slug}: flags `{' '.join(fn)}`; records "
                        f"{os.path.basename(old_recs[slug])} / "
                        f"{os.path.basename(new_recs[slug])}")
            for p in sb.patterns:
                text = sb.pattern_bytes(p.name)
                if p.name in canon and canon[p.name] != hashlib.sha256(text).hexdigest():
                    raise SystemExit(f"{p.name}: bench bytes do not hash to the "
                                     f"record's canonical_sha256")
                try:
                    from pcrecbench import capability as _cap
                    fs = "free-spacing" in _cap.pattern_requires(p)
                except Exception:  # a set with no requires tags
                    fs = False
                for form in FORMS:
                    ptext = text if form == "plain" else \
                        _rec.whole_subject_text(text, fs)
                    got = {}
                    for side in (old, new):
                        key = (side, tuple(fn), ptext)
                        if key not in cache:
                            cache[key] = emit(bins[side], shapes[side], fn, ptext,
                                              os.path.join(tmp, side))
                        got[side] = cache[key]
                    a, b = got[old], got[new]
                    if a is None and b is None:
                        verdict, ha, hb, ign = "refused-both", "-", "-", []
                    elif a is None or b is None:
                        verdict = "refused-old" if a is None else "refused-new"
                        ha = "-" if a is None else sha(a)
                        hb = "-" if b is None else sha(b)
                        ign = []
                    else:
                        na, nb, ign = normalize_pair(a, b)
                        ha, hb = sha(na), sha(nb)
                        verdict = "identical" if na == nb else "changed"
                    rows.append([slug, p.name, form, verdict, ha, hb,
                                 ",".join(ign) or "-"])
                print(f"  {slug} {p.name}", file=log)
    rows.sort()
    return meta, rows


def cross_check(rows, nullctl_path):
    """pcrec's nullctl.json keys `<pattern>|<config>` over three configs
    (auto-caps, auto-nocaps, vm-caps), PLAIN form only; values identical /
    changed / refused / refusal-mismatch. -> (agree, disagree list, n)."""
    with open(nullctl_path, encoding="utf-8") as fh:
        theirs = json.load(fh)
    slug_of = {"auto-caps": "auto-caps-simdna", "auto-nocaps": "auto-nocaps-simdna",
               "vm-caps": "vm-caps-simdna"}
    ours = {(r[0], r[1]): r[3] for r in rows if r[2] == "plain"}
    agree, disagree = 0, []
    for key, v in sorted(theirs.items()):
        pat, cfg = key.split("|", 1)
        o = ours.get((slug_of.get(cfg, cfg), pat))
        o_norm = {"refused-both": "refused"}.get(o, o)
        v_norm = {"refusal-mismatch": "refused-one"}.get(v, v)
        if o_norm in ("refused-old", "refused-new"):
            o_norm = "refused-one"
        if o_norm == v_norm:
            agree += 1
        else:
            disagree.append(f"{key}: ours={o} theirs={v}")
    return agree, disagree, len(theirs)


def render(meta, rows, xcheck_lines=()):
    counts = {}
    for r in rows:
        counts[r[3]] = counts.get(r[3], 0) + 1
    summary = "# verdicts: " + ", ".join(f"{k}={v}" for k, v in sorted(counts.items()))
    lines = list(meta) + [summary] + list(xcheck_lines) + ["\t".join(COLUMNS)]
    lines += ["\t".join(r) for r in rows]
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--subbench", required=True)
    ap.add_argument("--version", required=True)
    ap.add_argument("--old", required=True)
    ap.add_argument("--new", required=True)
    ap.add_argument("--engine", default="pcrec")
    ap.add_argument("--store", default=os.path.join(REPO_ROOT, "store"))
    ap.add_argument("--cross-check", help="pcrec's nullctl.json for this pair")
    ap.add_argument("--out", help="default: the reporter's lookup path")
    ap.add_argument("--check", action="store_true",
                    help="re-derive and diff against the committed file")
    a = ap.parse_args(argv)
    meta, rows = build_census(a.subbench, a.version, a.old, a.new, a.store, a.engine)
    xlines = []
    if a.cross_check:
        agree, dis, n = cross_check(rows, a.cross_check)
        xlines.append(f"# cross-check vs pcrec nullctl.json "
                      f"(sha256 {file_sha256(a.cross_check)}): {agree}/{n} "
                      f"agree" + (f"; DISAGREE: {'; '.join(dis)}" if dis else ""))
    text = render(meta, rows, xlines)
    out = a.out or census_path(a.subbench, a.version, a.engine, a.old, a.new)
    if a.check:
        with open(out, encoding="utf-8") as fh:
            committed = fh.read()
        # the cross-check line is an ANNOTATION made once, against a file
        # this repo does not hold -- compare everything else.
        strip = lambda t: "\n".join(ln for ln in t.split("\n")
                                    if not ln.startswith("# cross-check"))
        if strip(committed) != strip(text):
            print(f"{out}: DIFFERS from a fresh census", file=sys.stderr)
            return 1
        print(f"{out}: re-derives byte-identical")
        return 0
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote {out}: {len(rows)} rows")
    return 0


if __name__ == "__main__":
    sys.exit(main())
